// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

struct NotchStrings {
    let title: String
    let enable: String
    let description: String
    let display: String
    let automatic: String
    let builtIn: String
    let mainDisplay: String
    let hover: String
    let modules: String
    let events: String
    let clipboardActivity: String
    let captureActivity: String
    let privacy: String
    let open: String
    let collapse: String
    let pin: String
    let unpin: String
    let panel: String
    let dropHint: String
    let empty: String
    let volume: String
    let brightness: String
    let battery: String
    let onBattery: String
    let charging: String
    let charged: String
    let lowBattery: String
    let controls: String
    let system: String
    let disabled: String
    let files: String
    let showInCaptures: String
    let clipboardWindow: String
    let tools: String
    let size: String
    let compact: String
    let spacious: String
    let hoverExpand: String
    let shelfWindow: String
    let dragReveal: String
    let captureControls: String
    let quickPanel: String
    let appPanel: String
    let idleContent: String
    let idleNone: String
    let controlShortcuts: String
    let activity: String
    let playingMusic: String
    let custom: String
    let width: String
    let maximumHeight: String
    let sizeHint: String
    let hapticFeedback: String
    let hapticHint: String
}

extension FeatureStrings {
    static func notch(_ language: AppLanguage) -> NotchStrings {
        switch language {
        case .enUS: return .enUS
        case .ptBR: return .ptBR
        case .es: return .es
        case .de: return .de
        case .fr: return .fr
        case .it: return .it
        case .ru: return .ru
        case .tr: return .tr
        case .ja: return .ja
        case .ko: return .ko
        case .zhHans: return .zhHans
        case .zhTW: return .zhTW
        case .zhHK: return .zhHK
        }
    }
}

extension NotchStrings {
    static let enUS = NotchStrings(
        title: "Notch",
        enable: "Enable Notch",
        description: "Your music, controls and everyday tools, together at the top of your screen. Optional. Turn it off to keep using the separate panels.",
        display: "Display",
        automatic: "Automatic",
        builtIn: "Built-in display",
        mainDisplay: "Main display",
        hover: "Open when the pointer rests on the notch",
        modules: "What appears",
        events: "More options",
        clipboardActivity: "Notify when something is copied",
        captureActivity: "Show screenshot previews here",
        privacy: "Copied content stays private until you open the clipboard. These options follow the original feature’s settings.",
        open: "Open Notch",
        collapse: "Collapse",
        pin: "Keep open",
        unpin: "Allow automatic closing",
        panel: "Open app panel",
        dropHint: "Drop files here",
        empty: "Choose what appears in Notch settings.",
        volume: "Volume",
        brightness: "Brightness",
        battery: "Battery",
        onBattery: "On battery",
        charging: "Charging",
        charged: "Fully charged",
        lowBattery: "Low battery",
        controls: "Controls",
        system: "System",
        disabled: "Enable the corresponding feature to use it here.",
        files: "Files",
        showInCaptures: "Show in screenshots and videos",
        clipboardWindow: "Open clipboard history in the notch",
        tools: "Tools",
        size: "Size",
        compact: "Compact",
        spacious: "Spacious",
        hoverExpand: "Expand fully on hover",
        shelfWindow: "Open the file shelf in the notch",
        dragReveal: "Show a drop target while dragging",
        captureControls: "Show screen capture controls in the notch",
        quickPanel: "Open the quick panel in the notch",
        appPanel: "Open the app panel in the notch",
        idleContent: "While inactive",
        idleNone: "Nothing",
        controlShortcuts: "Controls and shortcuts",
        activity: "Activity",
        playingMusic: "Show music while playing",
        custom: "Custom",
        width: "Width",
        maximumHeight: "Maximum height",
        sizeHint: "Controls stay compact. Longer lists use up to this height.",
        hapticFeedback: "Haptic feedback",
        hapticHint: "A gentle tap when opening or switching sections, on a compatible trackpad."
    )

    static let ptBR = NotchStrings(
        title: "Notch",
        enable: "Ativar Notch",
        description: "Sua música, controles e ferramentas do dia a dia, juntos no topo da tela. Opcional. Desative para continuar usando os painéis separados.",
        display: "Tela",
        automatic: "Automática",
        builtIn: "Tela integrada",
        mainDisplay: "Tela principal",
        hover: "Abrir ao repousar o ponteiro sobre o notch",
        modules: "O que aparece",
        events: "Mais opções",
        clipboardActivity: "Avisar quando algo for copiado",
        captureActivity: "Mostrar prévias de capturas aqui",
        privacy: "O conteúdo copiado fica privado até você abrir o histórico. Estas opções respeitam os ajustes do recurso original.",
        open: "Abrir Notch",
        collapse: "Recolher",
        pin: "Manter aberto",
        unpin: "Permitir fechamento automático",
        panel: "Abrir painel do app",
        dropHint: "Solte arquivos aqui",
        empty: "Escolha o que aparece nos ajustes do Notch.",
        volume: "Volume",
        brightness: "Brilho",
        battery: "Bateria",
        onBattery: "Usando bateria",
        charging: "Carregando",
        charged: "Carga completa",
        lowBattery: "Bateria fraca",
        controls: "Controles",
        system: "Sistema",
        disabled: "Ative o recurso correspondente para usá-lo aqui.",
        files: "Arquivos",
        showInCaptures: "Aparecer em capturas de tela e vídeos",
        clipboardWindow: "Abrir o histórico de cópias no notch",
        tools: "Ferramentas",
        size: "Tamanho",
        compact: "Compacto",
        spacious: "Amplo",
        hoverExpand: "Expandir completamente ao passar o mouse",
        shelfWindow: "Abrir a área de arquivos no notch",
        dragReveal: "Mostrar um espaço para soltar ao arrastar",
        captureControls: "Mostrar os controles de captura no notch",
        quickPanel: "Abrir o painel rápido no notch",
        appPanel: "Abrir o painel do aplicativo no notch",
        idleContent: "Em repouso",
        idleNone: "Nada",
        controlShortcuts: "Controles e atalhos",
        activity: "Atividade",
        playingMusic: "Mostrar música durante a reprodução",
        custom: "Personalizado",
        width: "Largura",
        maximumHeight: "Altura máxima",
        sizeHint: "A área de controles fica compacta. Listas maiores usam até esta altura.",
        hapticFeedback: "Resposta tátil",
        hapticHint: "Um toque suave ao abrir ou trocar de seção, em um trackpad compatível."
    )

    static let es = NotchStrings(
        title: "Notch",
        enable: "Activar Notch",
        description: "Tu música, controles y herramientas cotidianas, juntos en la parte superior de la pantalla. Opcional. Desactívalo para seguir usando los paneles por separado.",
        display: "Pantalla",
        automatic: "Automática",
        builtIn: "Pantalla integrada",
        mainDisplay: "Pantalla principal",
        hover: "Abrir al dejar el puntero sobre el notch",
        modules: "Qué aparece",
        events: "Más opciones",
        clipboardActivity: "Avisar cuando se copie algo",
        captureActivity: "Mostrar vistas previas de capturas aquí",
        privacy: "El contenido copiado permanece privado hasta que abras el historial. Estas opciones respetan los ajustes de cada función.",
        open: "Abrir Notch",
        collapse: "Contraer",
        pin: "Mantener abierto",
        unpin: "Permitir cierre automático",
        panel: "Abrir panel de la app",
        dropHint: "Suelta archivos aquí",
        empty: "Elige qué aparece en los ajustes de Notch.",
        volume: "Volumen",
        brightness: "Brillo",
        battery: "Batería",
        onBattery: "Usando batería",
        charging: "Cargando",
        charged: "Carga completa",
        lowBattery: "Batería baja",
        controls: "Controles",
        system: "Sistema",
        disabled: "Activa la función correspondiente para usarla aquí.",
        files: "Archivos",
        showInCaptures: "Mostrar en capturas de pantalla y vídeos",
        clipboardWindow: "Abrir el historial del portapapeles en el notch",
        tools: "Herramientas",
        size: "Tamaño",
        compact: "Compacto",
        spacious: "Amplio",
        hoverExpand: "Expandir por completo al pasar el puntero",
        shelfWindow: "Abrir la bandeja de archivos en el notch",
        dragReveal: "Mostrar un destino al arrastrar",
        captureControls: "Mostrar controles de captura en el notch",
        quickPanel: "Abrir el panel rápido en el notch",
        appPanel: "Abrir el panel de la aplicación en el notch",
        idleContent: "En reposo",
        idleNone: "Nada",
        controlShortcuts: "Controles y atajos",
        activity: "Actividad",
        playingMusic: "Mostrar música durante la reproducción",
        custom: "Personalizado",
        width: "Ancho",
        maximumHeight: "Altura máxima",
        sizeHint: "Los controles se mantienen compactos. Las listas largas usan hasta esta altura.",
        hapticFeedback: "Respuesta háptica",
        hapticHint: "Un toque suave al abrir o cambiar de sección, en un trackpad compatible."
    )

    static let de = NotchStrings(
        title: "Notch",
        enable: "Notch aktivieren",
        description: "Musik, Steuerelemente und alltägliche Werkzeuge am oberen Bildschirmrand. Optional. Deaktiviere die Funktion, um die separaten Bereiche weiter zu nutzen.",
        display: "Bildschirm",
        automatic: "Automatisch",
        builtIn: "Integrierter Bildschirm",
        mainDisplay: "Hauptbildschirm",
        hover: "Öffnen, wenn der Zeiger auf der Notch ruht",
        modules: "Angezeigte Inhalte",
        events: "Weitere Optionen",
        clipboardActivity: "Beim Kopieren benachrichtigen",
        captureActivity: "Bildschirmfoto-Vorschauen hier anzeigen",
        privacy: "Kopierte Inhalte bleiben privat, bis du den Verlauf öffnest. Diese Optionen beachten die Einstellungen der jeweiligen Funktion.",
        open: "Notch öffnen",
        collapse: "Einklappen",
        pin: "Geöffnet lassen",
        unpin: "Automatisches Schließen erlauben",
        panel: "App-Panel öffnen",
        dropHint: "Dateien hier ablegen",
        empty: "Wähle die Inhalte in den Notch-Einstellungen.",
        volume: "Lautstärke",
        brightness: "Helligkeit",
        battery: "Batterie",
        onBattery: "Batteriebetrieb",
        charging: "Wird geladen",
        charged: "Vollständig geladen",
        lowBattery: "Niedriger Batteriestand",
        controls: "Steuerung",
        system: "System",
        disabled: "Aktiviere die entsprechende Funktion, um sie hier zu nutzen.",
        files: "Dateien",
        showInCaptures: "In Screenshots und Videos anzeigen",
        clipboardWindow: "Zwischenablageverlauf in der Notch öffnen",
        tools: "Werkzeuge",
        size: "Größe",
        compact: "Kompakt",
        spacious: "Geräumig",
        hoverExpand: "Beim Darüberfahren vollständig öffnen",
        shelfWindow: "Dateiablage im Notch öffnen",
        dragReveal: "Ablageziel beim Ziehen anzeigen",
        captureControls: "Aufnahmesteuerung im Notch anzeigen",
        quickPanel: "Schnellzugriff im Notch öffnen",
        appPanel: "App-Bereich im Notch öffnen",
        idleContent: "Im Ruhezustand",
        idleNone: "Nichts",
        controlShortcuts: "Steuerung und Kurzbefehle",
        activity: "Aktivität",
        playingMusic: "Musik während der Wiedergabe anzeigen",
        custom: "Eigene Größe",
        width: "Breite",
        maximumHeight: "Maximale Höhe",
        sizeHint: "Die Steuerung bleibt kompakt. Längere Listen nutzen bis zu dieser Höhe.",
        hapticFeedback: "Haptisches Feedback",
        hapticHint: "Ein sanfter Impuls beim Öffnen oder Wechseln von Bereichen auf einem kompatiblen Trackpad."
    )

    static let fr = NotchStrings(
        title: "Notch",
        enable: "Activer Notch",
        description: "Votre musique, vos commandes et vos outils du quotidien, réunis en haut de l’écran. Facultatif. Désactivez cette option pour continuer à utiliser les panneaux séparés.",
        display: "Écran",
        automatic: "Automatique",
        builtIn: "Écran intégré",
        mainDisplay: "Écran principal",
        hover: "Ouvrir lorsque le pointeur reste sur l’encoche",
        modules: "Contenu affiché",
        events: "Plus d’options",
        clipboardActivity: "Signaler les nouvelles copies",
        captureActivity: "Afficher les aperçus de captures ici",
        privacy: "Le contenu copié reste privé jusqu’à l’ouverture de l’historique. Ces options respectent les réglages de chaque fonction.",
        open: "Ouvrir Notch",
        collapse: "Réduire",
        pin: "Garder ouvert",
        unpin: "Autoriser la fermeture automatique",
        panel: "Ouvrir le panneau de l’app",
        dropHint: "Déposez des fichiers ici",
        empty: "Choisissez le contenu dans les réglages de Notch.",
        volume: "Volume",
        brightness: "Luminosité",
        battery: "Batterie",
        onBattery: "Sur batterie",
        charging: "En charge",
        charged: "Charge complète",
        lowBattery: "Batterie faible",
        controls: "Commandes",
        system: "Système",
        disabled: "Activez la fonction correspondante pour l’utiliser ici.",
        files: "Fichiers",
        showInCaptures: "Afficher dans les captures d’écran et les vidéos",
        clipboardWindow: "Ouvrir l’historique du presse-papiers dans l’encoche",
        tools: "Outils",
        size: "Taille",
        compact: "Compacte",
        spacious: "Spacieuse",
        hoverExpand: "Déployer au survol",
        shelfWindow: "Ouvrir la zone de fichiers dans le notch",
        dragReveal: "Afficher une zone de dépôt pendant le glissement",
        captureControls: "Afficher les commandes de capture dans le notch",
        quickPanel: "Ouvrir le panneau rapide dans le notch",
        appPanel: "Ouvrir le panneau de l’application dans le notch",
        idleContent: "Au repos",
        idleNone: "Rien",
        controlShortcuts: "Commandes et raccourcis",
        activity: "Activité",
        playingMusic: "Afficher la musique pendant la lecture",
        custom: "Personnalisé",
        width: "Largeur",
        maximumHeight: "Hauteur maximale",
        sizeHint: "Les commandes restent compactes. Les longues listes utilisent au plus cette hauteur.",
        hapticFeedback: "Retour haptique",
        hapticHint: "Une légère impulsion à l’ouverture ou au changement de rubrique, sur un trackpad compatible."
    )

    static let it = NotchStrings(
        title: "Notch",
        enable: "Attiva Notch",
        description: "Musica, controlli e strumenti quotidiani, insieme nella parte superiore dello schermo. Facoltativo. Disattiva questa opzione per continuare a usare i pannelli separati.",
        display: "Schermo",
        automatic: "Automatico",
        builtIn: "Schermo integrato",
        mainDisplay: "Schermo principale",
        hover: "Apri quando il puntatore si ferma sul notch",
        modules: "Contenuti visibili",
        events: "Altre opzioni",
        clipboardActivity: "Avvisa quando viene copiato qualcosa",
        captureActivity: "Mostra qui le anteprime delle catture",
        privacy: "Il contenuto copiato resta privato finché non apri la cronologia. Queste opzioni rispettano le impostazioni della funzione originale.",
        open: "Apri Notch",
        collapse: "Riduci",
        pin: "Mantieni aperto",
        unpin: "Consenti chiusura automatica",
        panel: "Apri pannello dell’app",
        dropHint: "Rilascia i file qui",
        empty: "Scegli cosa mostrare nelle impostazioni di Notch.",
        volume: "Volume",
        brightness: "Luminosità",
        battery: "Batteria",
        onBattery: "A batteria",
        charging: "In carica",
        charged: "Carica completa",
        lowBattery: "Batteria scarica",
        controls: "Controlli",
        system: "Sistema",
        disabled: "Attiva la funzione corrispondente per usarla qui.",
        files: "File",
        showInCaptures: "Mostra nelle schermate e nei video",
        clipboardWindow: "Apri la cronologia degli appunti nel notch",
        tools: "Strumenti",
        size: "Dimensioni",
        compact: "Compatto",
        spacious: "Ampio",
        hoverExpand: "Espandi completamente al passaggio del puntatore",
        shelfWindow: "Apri il ripiano dei file nel notch",
        dragReveal: "Mostra un’area di rilascio durante il trascinamento",
        captureControls: "Mostra i controlli di cattura nel notch",
        quickPanel: "Apri il pannello rapido nel notch",
        appPanel: "Apri il pannello dell’app nel notch",
        idleContent: "A riposo",
        idleNone: "Niente",
        controlShortcuts: "Controlli e scorciatoie",
        activity: "Attività",
        playingMusic: "Mostra la musica durante la riproduzione",
        custom: "Personalizzato",
        width: "Larghezza",
        maximumHeight: "Altezza massima",
        sizeHint: "I controlli restano compatti. Gli elenchi lunghi usano al massimo questa altezza.",
        hapticFeedback: "Feedback aptico",
        hapticHint: "Un leggero tocco quando apri o cambi sezione, su un trackpad compatibile."
    )

    static let ru = NotchStrings(
        title: "Notch",
        enable: "Включить Notch",
        description: "Музыка, управление и повседневные инструменты в верхней части экрана. Необязательно. Отключите, чтобы продолжить пользоваться отдельными панелями.",
        display: "Экран",
        automatic: "Автоматически",
        builtIn: "Встроенный экран",
        mainDisplay: "Основной экран",
        hover: "Открывать при наведении указателя",
        modules: "Что показывать",
        events: "Дополнительные параметры",
        clipboardActivity: "Сообщать о копировании",
        captureActivity: "Показывать здесь миниатюры снимков",
        privacy: "Скопированное содержимое скрыто до открытия истории. Эти параметры учитывают настройки соответствующей функции.",
        open: "Открыть Notch",
        collapse: "Свернуть",
        pin: "Оставить открытым",
        unpin: "Разрешить автоматическое закрытие",
        panel: "Открыть панель приложения",
        dropHint: "Перетащите файлы сюда",
        empty: "Выберите содержимое в настройках Notch.",
        volume: "Громкость",
        brightness: "Яркость",
        battery: "Аккумулятор",
        onBattery: "От аккумулятора",
        charging: "Заряжается",
        charged: "Полностью заряжен",
        lowBattery: "Низкий заряд",
        controls: "Управление",
        system: "Система",
        disabled: "Включите соответствующую функцию, чтобы использовать её здесь.",
        files: "Файлы",
        showInCaptures: "Показывать на снимках экрана и в видео",
        clipboardWindow: "Открывать историю буфера обмена в вырезе",
        tools: "Инструменты",
        size: "Размер",
        compact: "Компактный",
        spacious: "Просторный",
        hoverExpand: "Полностью раскрывать при наведении",
        shelfWindow: "Открывать полку файлов в вырезе",
        dragReveal: "Показывать область при перетаскивании",
        captureControls: "Показывать управление захватом в вырезе",
        quickPanel: "Открывать быструю панель в вырезе",
        appPanel: "Открывать панель приложения в вырезе",
        idleContent: "В состоянии покоя",
        idleNone: "Ничего",
        controlShortcuts: "Управление и быстрые действия",
        activity: "Активность",
        playingMusic: "Показывать музыку во время воспроизведения",
        custom: "Свой размер",
        width: "Ширина",
        maximumHeight: "Максимальная высота",
        sizeHint: "Панель управления остаётся компактной. Длинные списки используют не более этой высоты.",
        hapticFeedback: "Тактильный отклик",
        hapticHint: "Лёгкий отклик при открытии или смене раздела на совместимом трекпаде."
    )

    static let tr = NotchStrings(
        title: "Notch",
        enable: "Notch’u etkinleştir",
        description: "Müziğiniz, denetimleriniz ve günlük araçlarınız ekranın üst kısmında bir arada. İsteğe bağlıdır. Ayrı panelleri kullanmaya devam etmek için kapatın.",
        display: "Ekran",
        automatic: "Otomatik",
        builtIn: "Yerleşik ekran",
        mainDisplay: "Ana ekran",
        hover: "İşaretçi çentikte durduğunda aç",
        modules: "Gösterilenler",
        events: "Daha fazla seçenek",
        clipboardActivity: "Bir şey kopyalandığında bildir",
        captureActivity: "Ekran görüntüsü önizlemelerini burada göster",
        privacy: "Kopyalanan içerik, geçmişi açana kadar gizli kalır. Bu seçenekler ilgili özelliğin ayarlarına uyar.",
        open: "Notch’u aç",
        collapse: "Daralt",
        pin: "Açık tut",
        unpin: "Otomatik kapanmaya izin ver",
        panel: "Uygulama panelini aç",
        dropHint: "Dosyaları buraya bırakın",
        empty: "Notch ayarlarında gösterilecek içeriği seçin.",
        volume: "Ses düzeyi",
        brightness: "Parlaklık",
        battery: "Pil",
        onBattery: "Pil kullanılıyor",
        charging: "Şarj oluyor",
        charged: "Tam dolu",
        lowBattery: "Düşük pil",
        controls: "Denetimler",
        system: "Sistem",
        disabled: "Burada kullanmak için ilgili özelliği etkinleştirin.",
        files: "Dosyalar",
        showInCaptures: "Ekran görüntülerinde ve videolarda göster",
        clipboardWindow: "Pano geçmişini çentikte aç",
        tools: "Araçlar",
        size: "Boyut",
        compact: "Kompakt",
        spacious: "Geniş",
        hoverExpand: "İşaretçi üzerine geldiğinde tamamen aç",
        shelfWindow: "Dosya rafını çentikte aç",
        dragReveal: "Sürüklerken bırakma alanını göster",
        captureControls: "Ekran yakalama kontrollerini çentikte göster",
        quickPanel: "Hızlı paneli çentikte aç",
        appPanel: "Uygulama panelini çentikte aç",
        idleContent: "Boştayken",
        idleNone: "Hiçbir şey",
        controlShortcuts: "Kontroller ve kısayollar",
        activity: "Etkinlik",
        playingMusic: "Çalarken müziği göster",
        custom: "Özel",
        width: "Genişlik",
        maximumHeight: "En fazla yükseklik",
        sizeHint: "Denetimler kompakt kalır. Uzun listeler en fazla bu yüksekliği kullanır.",
        hapticFeedback: "Dokunsal geri bildirim",
        hapticHint: "Uyumlu bir izleme dörtgeninde açarken veya bölüm değiştirirken hafif bir dokunuş."
    )

    static let ja = NotchStrings(
        title: "ノッチ",
        enable: "ノッチを有効にする",
        description: "音楽、コントロール、毎日のツールを画面上部にまとめます。 必要に応じて有効にできます。オフにすると、個別のパネルを引き続き使用できます。",
        display: "ディスプレイ",
        automatic: "自動",
        builtIn: "内蔵ディスプレイ",
        mainDisplay: "メインディスプレイ",
        hover: "ノッチにポインタを置くと開く",
        modules: "表示する内容",
        events: "その他のオプション",
        clipboardActivity: "コピーしたときに通知",
        captureActivity: "スクリーンショットのプレビューをここに表示",
        privacy: "コピーした内容は履歴を開くまで表示されません。各機能の設定が適用されます。",
        open: "ノッチを開く",
        collapse: "閉じる",
        pin: "開いたままにする",
        unpin: "自動で閉じる",
        panel: "アプリのパネルを開く",
        dropHint: "ここにファイルをドロップ",
        empty: "ノッチの設定で表示する内容を選んでください。",
        volume: "音量",
        brightness: "明るさ",
        battery: "バッテリー",
        onBattery: "バッテリー使用中",
        charging: "充電中",
        charged: "充電完了",
        lowBattery: "バッテリー残量低下",
        controls: "コントロール",
        system: "システム",
        disabled: "対応する機能を有効にすると、ここで使用できます。",
        files: "ファイル",
        showInCaptures: "スクリーンショットと動画に表示",
        clipboardWindow: "クリップボード履歴をノッチで開く",
        tools: "ツール",
        size: "サイズ",
        compact: "コンパクト",
        spacious: "広め",
        hoverExpand: "ポインタを重ねたときに完全に開く",
        shelfWindow: "ファイルシェルフをノッチで開く",
        dragReveal: "ドラッグ中にドロップ先を表示",
        captureControls: "画面キャプチャの操作をノッチに表示",
        quickPanel: "クイックパネルをノッチで開く",
        appPanel: "アプリのパネルをノッチで開く",
        idleContent: "待機中",
        idleNone: "なし",
        controlShortcuts: "操作とショートカット",
        activity: "アクティビティ",
        playingMusic: "再生中の音楽を表示",
        custom: "カスタム",
        width: "幅",
        maximumHeight: "最大の高さ",
        sizeHint: "コントロールはコンパクトに保たれ、長いリストはこの高さまで広がります。",
        hapticFeedback: "触覚フィードバック",
        hapticHint: "対応するトラックパッドで、開くときやセクションを切り替えるときに軽い触覚を伝えます。"
    )

    static let ko = NotchStrings(
        title: "노치",
        enable: "노치 활성화",
        description: "음악, 제어 기능과 일상 도구를 화면 상단에 모아 보세요. 선택 기능입니다. 끄면 기존의 개별 패널을 계속 사용할 수 있습니다.",
        display: "디스플레이",
        automatic: "자동",
        builtIn: "내장 디스플레이",
        mainDisplay: "주 디스플레이",
        hover: "노치에 포인터를 두면 열기",
        modules: "표시할 항목",
        events: "추가 옵션",
        clipboardActivity: "복사할 때 알림",
        captureActivity: "스크린샷 미리보기를 여기에 표시",
        privacy: "복사한 내용은 기록을 열 때까지 비공개로 유지됩니다. 각 기능의 설정이 적용됩니다.",
        open: "노치 열기",
        collapse: "접기",
        pin: "열린 상태 유지",
        unpin: "자동으로 닫기 허용",
        panel: "앱 패널 열기",
        dropHint: "여기에 파일을 놓으세요",
        empty: "노치 설정에서 표시할 항목을 선택하세요.",
        volume: "음량",
        brightness: "밝기",
        battery: "배터리",
        onBattery: "배터리 사용 중",
        charging: "충전 중",
        charged: "충전 완료",
        lowBattery: "배터리 부족",
        controls: "제어",
        system: "시스템",
        disabled: "여기서 사용하려면 해당 기능을 활성화하세요.",
        files: "파일",
        showInCaptures: "스크린샷 및 동영상에 표시",
        clipboardWindow: "노치에서 클립보드 기록 열기",
        tools: "도구",
        size: "크기",
        compact: "작게",
        spacious: "넓게",
        hoverExpand: "포인터를 올리면 완전히 펼치기",
        shelfWindow: "파일 선반을 노치에서 열기",
        dragReveal: "드래그 중 놓을 영역 표시",
        captureControls: "화면 캡처 제어를 노치에 표시",
        quickPanel: "빠른 패널을 노치에서 열기",
        appPanel: "앱 패널을 노치에서 열기",
        idleContent: "대기 중",
        idleNone: "없음",
        controlShortcuts: "제어 및 단축키",
        activity: "활동",
        playingMusic: "재생 중인 음악 표시",
        custom: "사용자 지정",
        width: "너비",
        maximumHeight: "최대 높이",
        sizeHint: "제어 영역은 작게 유지되고 긴 목록은 이 높이까지 늘어납니다.",
        hapticFeedback: "햅틱 피드백",
        hapticHint: "호환되는 트랙패드에서 열거나 섹션을 바꿀 때 가볍게 진동합니다."
    )

    static let zhHans = NotchStrings(
        title: "刘海",
        enable: "启用刘海",
        description: "音乐、控制和日常工具，汇聚在屏幕顶部。 可选功能。关闭后可继续使用独立面板。",
        display: "显示器",
        automatic: "自动",
        builtIn: "内建显示器",
        mainDisplay: "主显示器",
        hover: "指针停留在刘海上时打开",
        modules: "显示内容",
        events: "更多选项",
        clipboardActivity: "复制时通知",
        captureActivity: "在此显示截屏预览",
        privacy: "复制的内容会保持私密，直到你打开历史记录。这些选项遵循原功能的设置。",
        open: "打开刘海",
        collapse: "收起",
        pin: "保持打开",
        unpin: "允许自动关闭",
        panel: "打开应用面板",
        dropHint: "将文件拖到这里",
        empty: "在刘海设置中选择要显示的内容。",
        volume: "音量",
        brightness: "亮度",
        battery: "电池",
        onBattery: "使用电池",
        charging: "正在充电",
        charged: "已充满",
        lowBattery: "电量低",
        controls: "控制",
        system: "系统",
        disabled: "启用相应功能后即可在此使用。",
        files: "文件",
        showInCaptures: "在截图和视频中显示",
        clipboardWindow: "在刘海中打开剪贴板历史记录",
        tools: "工具",
        size: "大小",
        compact: "紧凑",
        spacious: "宽敞",
        hoverExpand: "悬停时完全展开",
        shelfWindow: "在刘海中打开文件架",
        dragReveal: "拖动时显示放置区域",
        captureControls: "在刘海中显示屏幕捕获控制",
        quickPanel: "在刘海中打开快捷面板",
        appPanel: "在刘海中打开应用面板",
        idleContent: "闲置时",
        idleNone: "无",
        controlShortcuts: "控制与快捷操作",
        activity: "活动",
        playingMusic: "播放时显示音乐",
        custom: "自定义",
        width: "宽度",
        maximumHeight: "最大高度",
        sizeHint: "控制区域保持紧凑，较长的列表最多使用此高度。",
        hapticFeedback: "触觉反馈",
        hapticHint: "在兼容的触控板上，打开或切换区域时提供轻微触感。"
    )

    static let zhTW = NotchStrings(
        title: "瀏海",
        enable: "啟用瀏海",
        description: "音樂、控制項與日常工具，匯聚在螢幕頂端。 選用功能。關閉後可繼續使用獨立面板。",
        display: "顯示器",
        automatic: "自動",
        builtIn: "內建顯示器",
        mainDisplay: "主顯示器",
        hover: "指標停留在瀏海上時開啟",
        modules: "顯示內容",
        events: "更多選項",
        clipboardActivity: "複製時通知",
        captureActivity: "在此顯示截圖預覽",
        privacy: "複製的內容會保持私密，直到你開啟記錄。這些選項會遵循原功能的設定。",
        open: "開啟瀏海",
        collapse: "收合",
        pin: "保持開啟",
        unpin: "允許自動關閉",
        panel: "開啟 App 面板",
        dropHint: "將檔案拖到這裡",
        empty: "在瀏海設定中選擇要顯示的內容。",
        volume: "音量",
        brightness: "亮度",
        battery: "電池",
        onBattery: "使用電池",
        charging: "充電中",
        charged: "已充滿",
        lowBattery: "電量不足",
        controls: "控制項",
        system: "系統",
        disabled: "啟用對應功能後即可在此使用。",
        files: "檔案",
        showInCaptures: "在截圖與影片中顯示",
        clipboardWindow: "在瀏海中開啟剪貼簿記錄",
        tools: "工具",
        size: "大小",
        compact: "緊湊",
        spacious: "寬敞",
        hoverExpand: "游標停留時完全展開",
        shelfWindow: "在瀏海中開啟檔案架",
        dragReveal: "拖移時顯示放置區域",
        captureControls: "在瀏海中顯示螢幕擷取控制",
        quickPanel: "在瀏海中開啟快捷面板",
        appPanel: "在瀏海中開啟應用程式面板",
        idleContent: "閒置時",
        idleNone: "無",
        controlShortcuts: "控制與快捷操作",
        activity: "活動",
        playingMusic: "播放時顯示音樂",
        custom: "自訂",
        width: "寬度",
        maximumHeight: "最大高度",
        sizeHint: "控制區域保持精簡，較長的列表最多使用此高度。",
        hapticFeedback: "觸覺回饋",
        hapticHint: "在相容的觸控式軌跡板上，開啟或切換區域時提供輕微觸感。"
    )

    static let zhHK = NotchStrings(
        title: "瀏海",
        enable: "啟用瀏海",
        description: "音樂、控制項與日常工具，集中在螢幕頂端。 選用功能。關閉後可繼續使用獨立面板。",
        display: "顯示器",
        automatic: "自動",
        builtIn: "內置顯示器",
        mainDisplay: "主顯示器",
        hover: "指標停留在瀏海上時開啟",
        modules: "顯示內容",
        events: "更多選項",
        clipboardActivity: "複製時通知",
        captureActivity: "在此顯示螢幕截圖預覽",
        privacy: "複製的內容會保持私密，直到你開啟記錄。這些選項會遵從原功能的設定。",
        open: "開啟瀏海",
        collapse: "收合",
        pin: "保持開啟",
        unpin: "允許自動關閉",
        panel: "開啟 App 面板",
        dropHint: "將檔案拖到這裏",
        empty: "在瀏海設定中選擇要顯示的內容。",
        volume: "音量",
        brightness: "亮度",
        battery: "電池",
        onBattery: "使用電池",
        charging: "充電中",
        charged: "已充滿",
        lowBattery: "電量不足",
        controls: "控制項",
        system: "系統",
        disabled: "啟用相應功能後即可在此使用。",
        files: "檔案",
        showInCaptures: "在截圖與影片中顯示",
        clipboardWindow: "在瀏海中開啟剪貼簿記錄",
        tools: "工具",
        size: "大小",
        compact: "精簡",
        spacious: "寬敞",
        hoverExpand: "游標停留時完全展開",
        shelfWindow: "在瀏海中開啟檔案架",
        dragReveal: "拖移時顯示放置區域",
        captureControls: "在瀏海中顯示螢幕擷取控制",
        quickPanel: "在瀏海中開啟快捷面板",
        appPanel: "在瀏海中開啟應用程式面板",
        idleContent: "閒置時",
        idleNone: "無",
        controlShortcuts: "控制與快捷操作",
        activity: "活動",
        playingMusic: "播放時顯示音樂",
        custom: "自訂",
        width: "寬度",
        maximumHeight: "最大高度",
        sizeHint: "控制區域保持精簡，較長的列表最多使用此高度。",
        hapticFeedback: "觸覺回饋",
        hapticHint: "在兼容的觸控板上，開啟或切換區域時提供輕微觸感。"
    )

}
